package com.jcbase.model;

import com.jcbase.model.base.BaseConfigPushLog;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class ConfigPushLog extends BaseConfigPushLog<ConfigPushLog> {
	public static final ConfigPushLog dao = new ConfigPushLog().dao();
}
