package com.jcbase.model;

import com.jcbase.model.base.BaseHwPushStationYwb;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class HwPushStationYwb extends BaseHwPushStationYwb<HwPushStationYwb> {
	public static final HwPushStationYwb dao = new HwPushStationYwb().dao();
}
