package com.jcbase.model;

import com.jcbase.model.base.BaseHwPushStation;

/**
 * Generated by guozhen cheng.
 */
@SuppressWarnings("serial")
public class HwPushStation extends BaseHwPushStation<HwPushStation> {
	public static final HwPushStation dao = new HwPushStation().dao();
}
