package com.jcbase.model;

import com.jcbase.model.base.BasePlatformPoint;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class PlatformPoint extends BasePlatformPoint<PlatformPoint> {
	public static final PlatformPoint dao = new PlatformPoint().dao();
}
