package com.jcbase.model;

import com.jcbase.model.base.BasePushToken;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class PushToken extends BasePushToken<PushToken> {
	public static final PushToken dao = new PushToken().dao();
}
