package com.yanxin.common.model.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings({"serial", "unchecked"})
public abstract class BaseUpdateApp<M extends BaseUpdateApp<M>> extends Model<M> implements IBean {

	public M setId(java.lang.Integer id) {
		set("id", id);
		return (M)this;
	}
	
	public java.lang.Integer getId() {
		return getInt("id");
	}

	public M setMsg(java.lang.String msg) {
		set("msg", msg);
		return (M)this;
	}
	
	public java.lang.String getMsg() {
		return getStr("msg");
	}

	public M setUploadurl(java.lang.String uploadurl) {
		set("uploadurl", uploadurl);
		return (M)this;
	}
	
	public java.lang.String getUploadurl() {
		return getStr("uploadurl");
	}

	public M setSendTime(java.util.Date sendTime) {
		set("send_time", sendTime);
		return (M)this;
	}
	
	public java.util.Date getSendTime() {
		return get("send_time");
	}

	public M setCode(java.lang.String code) {
		set("code", code);
		return (M)this;
	}
	
	public java.lang.String getCode() {
		return getStr("code");
	}

	public M setYwbIdStr(java.lang.String ywbIdStr) {
		set("ywbIdStr", ywbIdStr);
		return (M)this;
	}
	
	public java.lang.String getYwbIdStr() {
		return getStr("ywbIdStr");
	}

	public M setDesc(java.lang.String desc) {
		set("desc", desc);
		return (M)this;
	}
	
	public java.lang.String getDesc() {
		return getStr("desc");
	}

}
