package com.yanxin.common.model.base;

import com.jfinal.plugin.activerecord.Model;
import com.jcbase.core.model.BaseModel;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings("serial")
public abstract class BaseSensor<M extends BaseSensor<M>> extends BaseModel<M> implements IBean {

	public void setSensorCode(java.lang.String sensorCode) {
		set("sensor_code", sensorCode);
	}

	public java.lang.String getSensorCode() {
		return get("sensor_code");
	}

	public void setBuilding_id(java.lang.Integer building_id) {
		set("building_id", building_id);
	}

	public java.lang.Integer getBuilding_id() {
		return get("building_id");
	}

	public void setAffiliation(java.lang.Long affiliation) {
		set("affiliation", affiliation);
	}

	public java.lang.Long getAffiliation() {
		return get("affiliation");
	}

	public void setId(java.lang.Long id) {
		set("id", id);
	}

	public java.lang.Long getId() {
		return get("id");
	}

	public void setCreateTime(java.util.Date createTime) {
		set("create_time", createTime);
	}

	public java.util.Date getCreateTime() {
		return get("create_time");
	}

	public java.util.Date getUpdateTime() {
		return get("update_time");
	}
	public void setUpdateTime(java.util.Date updateTime) {
		set("update_time", updateTime);
	}

	public void setStatus(java.lang.Integer status) {
		set("status", status);
	}

	public java.lang.Integer getStatus() {
		return get("status");
	}

	public void setName(java.lang.String name) {
		set("name", name);
	}

	public java.lang.String getName() {
		return get("name");
	}

	public void setPort(java.lang.Integer port) {
		set("port", port);
	}

	public java.lang.Integer getPort() {
		return get("port");
	}
	
	public void setPointNum(java.lang.Integer pointNum) {
		set("point_num", pointNum);
	}

	public java.lang.Integer getPointNum() {
		return get("point_num");
	}
	public void setSensor_id(java.lang.Integer sensor_id) {
		set("sensor_id", sensor_id);
	}

	public java.lang.Integer getSensor_id() {
		return get("sensor_id");
	}

}
