package com.yanxin.common.model.base;

import com.jfinal.plugin.activerecord.Model;
import com.jcbase.core.model.BaseModel;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings("serial")
public abstract class BasePoint<M extends BasePoint<M>> extends BaseModel<M> implements IBean {

	public void setId(java.lang.Integer id) {
		set("id", id);
	}

	public java.lang.Integer getId() {
		return get("id");
	}

	public void setPlatform_code(java.lang.String platform_code) {
		set("platform_code", platform_code);
	}

	public java.lang.String getPlatform_code() {
		return get("platform_code");
	}

	public void setPp_sensor_code(java.lang.String pp_sensor_code) {
		set("pp_sensor_code", pp_sensor_code);
	}

	public java.lang.String getPp_sensor_code() {
		return get("pp_sensor_code");
	}
	public void setImages(java.lang.String images) {
		set("images",images);
	}
	public java.lang.String getImages(){
		return get("images");
	}

	public void setStatus(java.lang.Integer status) {
		set("status", status);
	}

	public java.lang.Integer getStatus() {
		return get("status");
	}
	
	public void setDefault(java.lang.Integer defaul) {
		set("default", defaul);
	}

	public java.lang.Integer getDefault() {
		return get("defaul");
	}
	public void setCreateTime(java.util.Date createTime) {
		set("create_time", createTime);
	}

	public java.util.Date getCreateTime() {
		return get("create_time");
	}
    
	public java.lang.String getWarnTemp(){
		return get("warn_temp");
	}
	
	public void setWarnTemp(java.lang.String warnTemp){
		set("warn_temp",warnTemp);
	}
}
