package com.yanxin.common.model.base;

import com.jfinal.plugin.activerecord.Model;
import com.jcbase.core.model.BaseModel;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings({"serial", "unchecked"})
public abstract class BaseWorkArea<M extends BaseWorkArea<M>> extends BaseModel<M> implements IBean {

	public M setId(java.lang.Long id) {
		set("id", id);
		return (M)this;
	}
	
	public java.lang.Long getId() {
		return getLong("id");
	}

	public M setArea(java.lang.String area) {
		set("area", area);
		return (M)this;
	}
	
	public java.lang.String getArea() {
		return getStr("area");
	}

	public M setCreateTime(java.util.Date createTime) {
		set("create_time", createTime);
		return (M)this;
	}
	
	public java.util.Date getCreateTime() {
		return get("create_time");
	}
	
	public void setWaDesc(java.lang.String waDesc) {
		set("wa_desc", waDesc);
	}

	public java.lang.String getWaDesc() {
		return get("wa_desc");
	}

	public void setWaAddr(java.lang.String waAddr) {
		set("wa_addr", waAddr);
	}

	public java.lang.String getOpAddr() {
		return get("op_addr");
	}

}
