package com.yanxin.common.model.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings({"serial", "unchecked"})
public abstract class BaseTemp<M extends BaseTemp<M>> extends Model<M> implements IBean {

	public M setId(java.lang.Long id) {
		set("id", id);
		return (M)this;
	}
	
	public java.lang.Long getId() {
		return getLong("id");
	}

	public M setAvTemp(java.lang.Double avTemp) {
		set("av_temp", avTemp);
		return (M)this;
	}
	
	public java.lang.Double getAvTemp() {
		return getDouble("av_temp");
	}

	public M setTempSensorCode(java.lang.String tempSensorCode) {
		set("temp_sensor_code", tempSensorCode);
		return (M)this;
	}
	
	public java.lang.String getTempSensorCode() {
		return getStr("temp_sensor_code");
	}

	public M setCreateTime(java.util.Date createTime) {
		set("create_time", createTime);
		return (M)this;
	}
	
	public java.util.Date getCreateTime() {
		return get("create_time");
	}

	public M setMaxTemp(java.lang.Double maxTemp) {
		set("max_temp", maxTemp);
		return (M)this;
	}
	
	public java.lang.Double getMaxTemp() {
		return getDouble("max_temp");
	}

	public M setMinTemp(java.lang.Double minTemp) {
		set("min_temp", minTemp);
		return (M)this;
	}
	
	public java.lang.Double getMinTemp() {
		return getDouble("min_temp");
	}

	public M setStatus(java.lang.Integer status) {
		set("status", status);
		return (M)this;
	}
	
	public java.lang.Integer getStatus() {
		return getInt("status");
	}

	public M setPointType(java.lang.String pointType) {
		set("point_type", pointType);
		return (M)this;
	}
	
	public java.lang.String getPointType() {
		return getStr("point_type");
	}

	public M setColorBar(java.lang.Integer colorBar) {
		set("color_bar", colorBar);
		return (M)this;
	}
	
	public java.lang.Integer getColorBar() {
		return getInt("color_bar");
	}

}
