package com.yanxin.common.model.base;

import com.jcbase.core.model.BaseModel;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings("serial")
public abstract class BaseWarn<M extends BaseWarn<M>> extends BaseModel<M> implements IBean {

	public void setId(int id) {
		set("id", id);
	}

	public int getId() {
		return get("id");
	}

	public void setPointType(java.lang.String pointType) {
		set("point_type", pointType);
	}

	public java.lang.String getPointType() {
		return get("point_type");	
	}

	public void setMaxTemp(java.lang.Double maxTemp) {
		set("max_temp", maxTemp);
	}

	public java.lang.Double getMaxTemp() {
		return get("max_temp");
	}

	public void setSensorCode(java.lang.String sensorCode) {
		set("sensor_code", sensorCode);
	}

	public java.lang.String getSensorCode() {
		return get("sensor_code");
	}


	public void setCreateTime(java.util.Date createTime) {
		set("create_time", createTime);
	}

	public java.util.Date getCreateTime() {
		return get("create_time");
	}

}
