package com.jcbase.model.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings("serial")
public abstract class BasePushToken<M extends BasePushToken<M>> extends Model<M> implements IBean {

	public void setId(java.lang.Long id) {
		set("id", id);
	}

	public java.lang.Long getId() {
		return get("id");
	}

	public void setToken(java.lang.String token) {
		set("token", token);
	}

	public java.lang.String getToken() {
		return get("token");
	}

	public void setAuth(java.lang.Integer auth) {
		set("auth", auth);
	}

	public java.lang.Integer getAuth() {
		return get("auth");
	}

	public void setYwb(java.lang.Integer ywb) {
		set("ywb", ywb);
	}

	public java.lang.Integer getYwb() {
		return get("ywb");
	}

}
