package com.jcbase.model.base;
import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings({"serial", "unchecked"})
public abstract class BasePlatformPoint<M extends BasePlatformPoint<M>> extends Model<M> implements IBean {

	public M setId(java.lang.Long id) {
		set("id", id);
		return (M)this;
	}
	
	public java.lang.Long getId() {
		return getLong("id");
	}

	public M setPlatformCode(java.lang.String platformCode) {
		set("platform_code", platformCode);
		return (M)this;
	}
	
	public java.lang.String getPlatformCode() {
		return getStr("platform_code");
	}

	public M setPpSensorCode(java.lang.String ppSensorCode) {
		set("pp_sensor_code", ppSensorCode);
		return (M)this;
	}
	
	public java.lang.String getPpSensorCode() {
		return getStr("pp_sensor_code");
	}

	public M setImages(java.lang.String images) {
		set("images", images);
		return (M)this;
	}
	
	public java.lang.String getImages() {
		return getStr("images");
	}

	public M setStatus(java.lang.Integer status) {
		set("status", status);
		return (M)this;
	}
	
	public java.lang.Integer getStatus() {
		return getInt("status");
	}

	public M setDefaul(java.lang.Integer defaul) {
		set("defaul", defaul);
		return (M)this;
	}
	
	public java.lang.Integer getDefaul() {
		return getInt("defaul");
	}

	public M setCreateTime(java.util.Date createTime) {
		set("create_time", createTime);
		return (M)this;
	}
	
	public java.util.Date getCreateTime() {
		return get("create_time");
	}

	public M setPointType(java.lang.String pointType) {
		set("point_type", pointType);
		return (M)this;
	}
	
	public java.lang.String getPointType() {
		return getStr("point_type");
	}

	public M setWarnTemp(java.lang.Integer warnTemp) {
		set("warn_temp", warnTemp);
		return (M)this;
	}
	
	public java.lang.Integer getWarnTemp() {
		return getInt("warn_temp");
	}

	public M setIslook(java.lang.Integer islook) {
		set("islook", islook);
		return (M)this;
	}
	
	public java.lang.Integer getIslook() {
		return getInt("islook");
	}

	public M setMaxTemp(java.lang.Double maxTemp) {
		set("max_temp", maxTemp);
		return (M)this;
	}
	
	public java.lang.Double getMaxTemp() {
		return getDouble("max_temp");
	}

	public M setCurrentTemp(java.lang.Double currentTemp) {
		set("current_temp", currentTemp);
		return (M)this;
	}
	
	public java.lang.Double getCurrentTemp() {
		return getDouble("current_temp");
	}

	public M setUpdateTime(java.util.Date updateTime) {
		set("update_time", updateTime);
		return (M)this;
	}
	
	public java.util.Date getUpdateTime() {
		return get("update_time");
	}

	public M setHistoryMaxTemp(java.lang.Double historyMaxTemp) {
		set("history_max_temp", historyMaxTemp);
		return (M)this;
	}
	
	public java.lang.Double getHistoryMaxTemp() {
		return getDouble("history_max_temp");
	}

}
