package com.jcbase.model.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings("serial")
public abstract class BaseHwPushStationYwb<M extends BaseHwPushStationYwb<M>> extends Model<M> implements IBean {

	public void setId(java.lang.Integer id) {
		set("id", id);
	}

	public java.lang.Integer getId() {
		return get("id");
	}

	public void setToken(java.lang.String token) {
		set("token", token);
	}

	public java.lang.String getToken() {
		return get("token");
	}

	public void setYwb(java.lang.Integer ywb) {
		set("ywb", ywb);
	}

	public java.lang.Integer getYwb() {
		return get("ywb");
	}

	public void setStationId(java.lang.Integer stationId) {
		set("station_id", stationId);
	}

	public java.lang.Integer getStationId() {
		return get("station_id");
	}

	public void setStationName(java.lang.String stationName) {
		set("station_name", stationName);
	}

	public java.lang.String getStationName() {
		return get("station_name");
	}

	public void setUsername(java.lang.String username) {
		set("username", username);
	}

	public java.lang.String getUsername() {
		return get("username");
	}

	public void setAuth(java.lang.Integer auth) {
		set("auth", auth);
	}

	public java.lang.Integer getAuth() {
		return get("auth");
	}

	public void setCreateTime(java.util.Date createTime) {
		set("create_time", createTime);
	}

	public java.util.Date getCreateTime() {
		return get("create_time");
	}

}
