package com.yanxin.common.model;

import com.jfinal.plugin.activerecord.ActiveRecordPlugin;

/**
 * Generated by JFinal, do not modify this file.
 * <pre>
 * Example:
 * public void configPlugin(Plugins me) {
 *     ActiveRecordPlugin arp = new ActiveRecordPlugin(...);
 *     _MappingKit.mapping(arp);
 *     me.add(arp);
 * }
 * </pre>
 */
public class _MappingKit {
	
	public static void mapping(ActiveRecordPlugin arp) {
		arp.addMapping("update_app", "id", UpdateApp.class);
		arp.addMapping("images", "id", Images.class);
		arp.addMapping("temp", "id", Temp.class);
		arp.addMapping("warn", "id", Warn.class);
		arp.addMapping("warnimages", "id", Warnimages.class);
		arp.addMapping("images_high", "id", ImagesHigh.class);
	}
}

