package com.yanxin.common.model;

import com.jfinal.plugin.activerecord.Page;
import com.yanxin.common.model.base.BaseImages;

/**
 * Generated by JFinal.
 */

public class Images extends BaseImages<Images> {
	
	private static final long serialVersionUID = -4833191302759204592L; 
	public static final Images me = new Images();
	
	
	public Page<Images> getImagesPage(int page, int rows, String op_class, String station, String building, String sensor,String createTimeString, String endTimeString,
			String orderbyStr) {
		StringBuffer sqlExceptSelect=new StringBuffer();
		if(station==null){
			sqlExceptSelect.append("FROM images, temp, sensor,building,station,operation_class WHERE operation_class.id=station.op_id AND operation_class.id="+op_class+" AND station.id=building.station_id AND building.id=sensor.building_id AND images.im_sensor_code = temp.temp_sensor_code AND images.create_time = temp.create_time AND images.im_sensor_code=sensor.sensor_code  AND images.create_time> '"+createTimeString+"' AND images.create_time< '"+endTimeString+"' ORDER BY images.create_time DESC");
		}else {
			if(building==null){
				sqlExceptSelect.append("FROM images, temp, sensor,building,station,operation_class WHERE operation_class.id=station.op_id AND station.id=building.station_id AND station.id="+station+" AND building.id=sensor.building_id AND images.im_sensor_code = temp.temp_sensor_code AND images.create_time = temp.create_time AND images.im_sensor_code=sensor.sensor_code  AND images.create_time> '"+createTimeString+"' AND images.create_time< '"+endTimeString+"' ORDER BY images.create_time DESC");
			}else {
				if(sensor==null){
					sqlExceptSelect.append("FROM images, temp, sensor,building WHERE building.id=sensor.building_id AND building.id="+building+" AND images.im_sensor_code = temp.temp_sensor_code AND images.create_time = temp.create_time AND images.im_sensor_code=sensor.sensor_code  AND images.create_time> '"+createTimeString+"' AND images.create_time< '"+endTimeString+"' ORDER BY images.create_time DESC");
				}else {
					String[] s=sensor.split("/");
					String sensorCodeString=s[0];
					String point_type=s[1];
					sqlExceptSelect.append("FROM images, temp, sensor,building WHERE building.id=sensor.building_id AND images.im_sensor_code = temp.temp_sensor_code AND images.create_time = temp.create_time AND images.im_sensor_code=sensor.sensor_code AND im_sensor_code = '"+sensorCodeString+"' AND images.point_type=temp.point_type AND images.point_type="+point_type+"  AND images.create_time> '"+createTimeString+"' AND images.create_time< '"+endTimeString+"' ORDER BY images.create_time DESC");

				}
			}
		}
		String select="SELECT DISTINCT building.building_name,images.url as url, temp.av_temp as av, temp.max_temp as max, temp.min_temp as min, images.id as id, images.create_time as create_time, images.im_sensor_code as im_sensor_code,sensor.name as sensor_name";
		System.out.println(select+sqlExceptSelect.toString());
		return this.paginate(page, rows, select, sqlExceptSelect.toString());
	}


	
}
