package com.yanxin.common.model;


import java.util.ArrayList;
import java.util.Date;
import java.util.HashSet;
import java.util.List;
import java.util.Set;

import com.jcbase.core.model.Condition;
import com.jcbase.core.model.Operators;
import com.jcbase.core.util.CommonUtils;
import com.jcbase.core.util.MyDigestUtils;
import com.jcbase.core.view.InvokeResult;
import com.jcbase.model.SysRole;
import com.jcbase.model.SysUser;
import com.jfinal.kit.StrKit;
import com.jfinal.plugin.activerecord.Db;
import com.jfinal.plugin.activerecord.Page;
import com.jfinal.plugin.activerecord.Record;
import com.yanxin.common.model.base.BaseOperationClass;

/**
 * Generated by JFinal.
 */
public class OperationClass extends BaseOperationClass<OperationClass> {

	/**
	 * 
	 */
	private static final long serialVersionUID = -4833191302759104592L; 
	public static final OperationClass me = new OperationClass();
	
	public Page<OperationClass> getOperationClassPage(int page, int rows, String keyword,
			String orderbyStr) {
		Set<Condition> conditions=new HashSet<Condition>();
		List<Object> outConditionValues=new ArrayList<Object>();
		if(CommonUtils.isNotEmpty(keyword)){
			conditions.add(new Condition("op_name",Operators.LIKE,keyword));
		}
		//String select="select su.*, (select group_concat(name) as opNames from sys_user where sys_user.id=su.op_manager) as opNames";
		String select="select su.*";
		StringBuffer sqlExceptSelect=new StringBuffer();
		sqlExceptSelect.append("from operation_class su"+super.getWhereSql(conditions, outConditionValues));
		return this.paginate(page, rows, select, sqlExceptSelect.toString());
	}
	/**
	 * 
	 * @param page
	 * @param rows
	 * @param username
	 * @param orderbyStr
	 * @return
	 */
	public Page<OperationClass> getOperationClassPageNew(int page, int rows, String username,int workArea,
			String orderbyStr) {
			
		Set<Condition> conditions=new HashSet<Condition>();
		List<Object> outConditionValues=new ArrayList<Object>();
		
		SysUser user = SysUser.me.getByName(username);
		
		if(user.getUserType().intValue() == new Integer(0).intValue()){
			if(workArea>0){
				String select = "select su.*, work_area.area ";
				String sqlExceptSelect = "from operation_class su,work_area where su.work_area_id=work_area.id ";
				return this.paginate(page, rows, select, sqlExceptSelect);
			}else {
				String select = "select su.*, work_area.area ";
				String sqlExceptSelect = "from operation_class su,work_area where su.work_area_id=work_area.id ";
				return this.paginate(page, rows, select, sqlExceptSelect);
			}
			
		}else {
			int tempid = 0;
			if(workArea>0){
				tempid = workArea;
			}else{
				tempid = user.getWork_area_id();
			}
			if(user != null ){
				conditions.add(new Condition("work_area_id",Operators.LIKE,tempid));
			}
			String select="select su.*, (select area from work_area where id="+tempid+") as area";
			StringBuffer sqlExceptSelect=new StringBuffer();
			sqlExceptSelect.append("from operation_class su"+super.getWhereSql(conditions, outConditionValues));
			return this.paginate(page, rows, select, sqlExceptSelect.toString());
		}
	}

	
	//用户名是否存在
	public boolean hasExist(String name){
		Set<Condition> conditions=new HashSet<Condition>();
		conditions.add(new Condition("op_name",Operators.EQ,name));
		long num=this.getCount(conditions);
		return num>0?true:false;
	}
	
	
	public InvokeResult save(Integer id, String op_name, String op_desc, String op_addr) {
		// TODO Auto-generated method stub
		if(id!=null){
			OperationClass opclass=this.findById(id);
			/*if(op_manager==0) {
				opclass.set("op_name", op_name).set("op_desc",op_desc).set("op_addr",op_addr).update();
			}
			else {*/
			opclass.set("op_name", op_name).set("op_desc",op_desc).set("op_addr",op_addr).update();
			//}
			//int b=Db.update("update sys_user set operation_class_id=(select id from operation_class where op_manager=?) where id=?",op_manager,op_manager);
		}else {
			if(this.hasExist(op_name)){
				return InvokeResult.failure("运维班已存在");
			}else{
				new OperationClass().set("op_name", op_name).set("op_desc",op_desc).set("op_addr",op_addr).set("create_time", new Date()).save();
				//int b=Db.update("update sys_user set operation_class_id=(select id from operation_class where op_manager=?) where id=?",op_manager,op_manager);
			}
		}
		
		return InvokeResult.success();
	} 
	
	public InvokeResult saveNew(Integer id, String op_name, Integer workAreaId,String op_desc, String op_addr) {
		// TODO Auto-generated method stub
		if(id!=null){
			OperationClass opclass=this.findById(id);
			/*if(op_manager==0) {
				opclass.set("op_name", op_name).set("op_desc",op_desc).set("op_addr",op_addr).update();
			}
			else {*/
			opclass.set("op_name", op_name).set("work_area_id",workAreaId).set("op_desc",op_desc).set("op_addr",op_addr).update();
			//}
			//int b=Db.update("update sys_user set operation_class_id=(select id from operation_class where op_manager=?) where id=?",op_manager,op_manager);
		}else {
			if(this.hasExist(op_name)){
				return InvokeResult.failure("运维班已存在");
			}else{
				new OperationClass().set("op_name", op_name).set("work_area_id",workAreaId).set("op_desc",op_desc).set("op_addr",op_addr).set("create_time", new Date()).save();
				//int b=Db.update("update sys_user set operation_class_id=(select id from operation_class where op_manager=?) where id=?",op_manager,op_manager);
			}
		}
		
		return InvokeResult.success();
	} 
	
	
	
	public InvokeResult deleteData(Integer id) {
		this.deleteById(id);
		return InvokeResult.success();
	}
	
}
