package com.yanxin.common.model;

import com.jfinal.plugin.activerecord.Page;
import com.yanxin.common.model.base.BaseTemp;

/**
 * Generated by Guozhen Cheng.
 */
@SuppressWarnings("serial")
public class Temp extends BaseTemp<Temp> {
	private static final long serialVersionUID = -5838191302759104592L; 
	public static final Temp me = new Temp();
	
	public Page<Temp> getTempPage(int page, int rows, String createTimeString, String endTimeString, String sensorCodeString, String point_type,
			String orderbyStr) {
		StringBuffer sqlExceptSelect=new StringBuffer();
		String sqlString = "FROM temp,platform_point,sensor,building,station,operation_class,work_area WHERE temp.status=0 AND temp.temp_sensor_code=sensor.sensor_code AND sensor.sensor_code=platform_point.pp_sensor_code AND temp.point_type=platform_point.point_type AND sensor.building_id=building.id AND building.station_id=station.id AND station.op_id=operation_class.id AND operation_class.work_area_id=work_area.id AND temp_sensor_code ='"+sensorCodeString+"' AND temp.point_type= "+point_type+" AND temp.status=0 AND temp.create_time>'"+createTimeString+"' AND temp.create_time<'"+endTimeString+"' ";
		sqlExceptSelect.append(sqlString);
		String select="SELECT temp.*,CONCAT(sensor.`name`,platform_code) as sensorName,building.building_name,station.station_name,operation_class.op_name,work_area.area ";
		System.out.println(sqlString+select+"111");
		
		sqlExceptSelect.append(orderbyStr);
		
		return this.paginate(page, rows, select, sqlExceptSelect.toString());
	}
	
	public Page<Temp> getTempPage(int page, int rows, String sensorCodeString, String point_type,
			String orderbyStr) {
		StringBuffer sqlExceptSelect=new StringBuffer();
		String sqlString = "FROM temp,platform_point WHERE temp.status=0 AND temp.temp_sensor_code=platform_point.pp_sensor_code AND temp.point_type=platform_point.point_type AND temp_sensor_code ='"+sensorCodeString+"' AND temp.point_type= "+point_type+" ORDER BY temp.create_time DESC";
		sqlExceptSelect.append(sqlString);
		String select="SELECT temp.*,platform_point.warn_temp ";
		
		sqlExceptSelect.append(orderbyStr);
		
		return this.paginate(page, rows, select, sqlExceptSelect.toString());
	}
}
