package com.yanxin.common.model;

import com.yanxin.common.model.base.BaseWarnimages;

/**
 * Generated by JFinal.
 */

public class Warnimages extends BaseWarnimages<Warnimages> {
	/**
	 * 
	 */
	private static final long serialVersionUID = -1904055002537105635L;
	public static final Warnimages me = new Warnimages();
	
}
