package com.yanxin.common.model;


import java.util.ArrayList;
import java.util.Date;
import java.util.HashSet;
import java.util.List;
import java.util.Set;

import com.jcbase.core.model.Condition;
import com.jcbase.core.model.Operators;
import com.jcbase.core.util.CommonUtils;
import com.jcbase.core.view.InvokeResult;
import com.jfinal.plugin.activerecord.Page;
import com.yanxin.common.model.base.BaseOperationClass;

/**
 * Generated by JFinal.
 */
public class Warn extends BaseOperationClass<Warn> {

/**
	 * 
	 */
	private static final long serialVersionUID = -5833191302759104592L; 
	public static final Warn me = new Warn();
	
	public Page<Warn> getWarnPage(int page, int rows, String op_class, String station, String building, String sensor,
			String orderbyStr) {
		StringBuffer sqlExceptSelect=new StringBuffer();
		/*Set<Condition> conditions=new HashSet<Condition>();
		List<Object> outConditionValues=new ArrayList<Object>();*/
		/*conditions.add(new Condition("warn.sensor_code",Operators.EQ,"sensor.sensor_code"));
		conditions.add(new Condition("warn.point_type",Operators.EQ,"platform_point.point_type"));
		conditions.add(new Condition("platform_point.pp_sensor_code",Operators.EQ,"sensor.sensor_code"));
		conditions.add(new Condition("sensor.building_id",Operators.EQ,"building.id"));
		conditions.add(new Condition("building.station_id",Operators.EQ,"station.id"));
		conditions.add(new Condition("operation_class.id",Operators.EQ,"station.op_id"));*/
		
		if(station==null){
			sqlExceptSelect.append("FROM warn,platform_point,building,sensor,station,operation_class WHERE warn.sensor_code=sensor.sensor_code AND warn.point_type=platform_point.point_type AND platform_point.pp_sensor_code=sensor.sensor_code AND sensor.building_id=building.id AND building.station_id=station.id AND station.op_id=operation_class.id AND operation_class.id="+op_class);
		}else {
			if(building==null){
				sqlExceptSelect.append("FROM warn,platform_point,building,sensor,station,operation_class WHERE warn.sensor_code=sensor.sensor_code AND warn.point_type=platform_point.point_type AND platform_point.pp_sensor_code=sensor.sensor_code AND sensor.building_id=building.id AND building.station_id=station.id AND station.op_id=operation_class.id AND station.id="+station);
			}else {
				if(sensor==null){
					sqlExceptSelect.append("FROM warn,platform_point,building,sensor,station,operation_class WHERE warn.sensor_code=sensor.sensor_code AND warn.point_type=platform_point.point_type AND platform_point.pp_sensor_code=sensor.sensor_code AND sensor.building_id=building.id AND building.station_id=station.id AND station.op_id=operation_class.id AND building.id="+building);
				}else {
					String[] s=sensor.split("/");
					String sensorCodeString=s[0];
					String point_type=s[1];
					sqlExceptSelect.append("FROM warn,platform_point,building,sensor,station,operation_class WHERE warn.sensor_code=sensor.sensor_code AND warn.point_type=platform_point.point_type AND platform_point.pp_sensor_code=sensor.sensor_code AND sensor.building_id=building.id AND building.station_id=station.id AND station.op_id=operation_class.id AND warn.sensor_code='"+sensorCodeString+"' AND warn.point_type="+point_type);

				}
			}
		}
		String select="SELECT warn.*, CONCAT(`name`,platform_code) as sensorName,building.building_name,station.station_name,operation_class.op_name";
		//sqlExceptSelect.append("FROM warn,platform_point,building,sensor,station,operation_class WHERE warn.sensor_code=sensor.sensor_code AND warn.point_type=platform_point.point_type AND platform_point.pp_sensor_code=sensor.sensor_code AND sensor.building_id=building.id AND building.station_id=station.id AND station.op_id=operation_class.id");
		/*sqlExceptSelect.replace(313, 318, "and");*/
		return this.paginate(page, rows, select, sqlExceptSelect.toString());
	}
	
	public InvokeResult deleteData(Integer id) {
		this.deleteById(id);
		return InvokeResult.success();
	}
	
}
